name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  DOCKER_IMAGE: briskly-generate-flash-cards-app
  CONTAINER_NAME: briskly-generate-flash-cards
  ECR_REPOSITORY_URL: 022559444262.dkr.ecr.us-east-1.amazonaws.com/briskly-generate-flash-cards
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker pull $ECR_REPOSITORY_URL/$DOCKER_IMAGE:latest
            docker run -d -p 80:80 --name $CONTAINER_NAME $ECR_REPOSITORY_URL/$DOCKER_IMAGE:latest
