name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  DOCKER_IMAGE: briskly-generate-flash-cards-app
  ECR_CONTAINER_NAME: briskly-generate-flash-cards
  ECR_REPOSITORY_URL: 022559444262.dkr.ecr.us-east-1.amazonaws.com
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  EC2_REMOTE_HOST: ec2-107-23-241-18.compute-1.amazonaws.com
  EC2_REMOTE_USER: ubuntu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-region: us-east-1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $ECR_REPOSITORY_URL/$ECR_CONTAINER_NAME:latest .
          docker push $ECR_REPOSITORY_URL/$ECR_CONTAINER_NAME:latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >> ~/.ssh/config << END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END

      - name: Docker run
        run: |
          docker stop $DOCKER_IMAGE || true
          docker rm $DOCKER_IMAGE || true
          docker pull $ECR_REPOSITORY_URL/$ECR_CONTAINER_NAME:latest
          docker run -d --name $DOCKER_IMAGE $ECR_REPOSITORY_URL/$ECR_CONTAINER_NAME:latest
